/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116395-g4acb9b7d10-20240723"
#endif /* AVUTIL_FFVERSION_H */
